version: "3"
services:
  backend:
    container_name: backend
    build: .
    volumes:
      - .:/app
    environment:
      DATABASE_URL: ${DATABASE_URL}
    restart: always
    ports:
     - "5000:5000"
    depends_on:
      - redis
      - cboe-db
  cboe-db:
    image: "postgres:10-alpine"
    restart: always
    ports:
      - "5433:5432"
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  beat:
    command: celery -A tasks beat --loglevel=debug
    build:
      context: celery
      dockerfile: Dockerfile
    environment:
    environment:
      DATA_FILE: ${DATA_FILE}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
    volumes:
      - ./celery:/queue
  worker:
    command: celery -A tasks worker --loglevel=debug
    build:
      context: celery
      dockerfile: Dockerfile
    environment:
    environment:
      DATA_FILE: ${DATA_FILE}
      PITCH_ENDPOINT: ${PITCH_ENDPOINT}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    depends_on:
      - redis
    volumes:
      - ./celery:/queue
  monitor:
    build:
      context: celery
      dockerfile: Dockerfile
    environment:
      DATA_FILE: ${DATA_FILE}
      PITCH_ENDPOINT: ${PITCH_ENDPOINT}
    ports:
     - "5555:5555"
    entrypoint: flower
    command:  -A tasks --port=5555 --broker=redis://redis:6379/0
    depends_on:
      - redis
  redis:
    image: redis
    ports:
     - "6379:6379"