"""empty message

Revision ID: 0cff33bb194d
Revises: 
Create Date: 2019-10-24 07:30:10.721955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cff33bb194d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_type_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['message_type_id'], ['message_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('message_types', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_types', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('messages')
    # ### end Alembic commands ###
