"""empty message

Revision ID: e3796bc7835b
Revises: 
Create Date: 2019-10-26 02:50:37.646090

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3796bc7835b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_type_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['message_type_id'], ['message_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('message_type', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('message_type', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_table('message')
    # ### end Alembic commands ###
